instagram/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from .views import landing_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing_page, name='landing_page'),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^member/', include('member.urls', namespace='member')),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

instagram/post/urls.py
from django.conf.urls import url

from post import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^delete/(?P<post_pk>\d+)/$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like$', views.post_like_toggle, name='post_like_toggle'),
    url(r'^comment/(?P<post_pk>\d+)/$', views.add_comment, name='add_comment'),
    url(r'^comment/(?P<comment_pk>\d+)/delete/$', views.delete_comment, name='delete_comment'),
]

instagram/post/models.py
from django.db import models

# Create your models here.
from config import settings


class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(author__isnull=False)


class Post(models.Model):
    objects = PostManager()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to='post',
        blank=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = [
            "-created_at",
        ]
    def __str__(self):
        return f'{self.author} - {self.pk}'


class PostComment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    content = models.TextField(
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.content

    class Meta:
        ordering = [
            "created_at",
        ]

instagram/post/forms.py
from django import forms

from .models import Post, PostComment


class PostForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['author'].required = True

    class Meta:
        model = Post
        fields = [
            "photo",
        ]

class PostCommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
    )

    class Meta:
        model = PostComment
        fields = [
            "content",
        ]
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                }
            )
        }

        # def is_valid(self):
        # self.instance.post
        # return super(PostCommentForm, self).form_valid()

instagram/post/views.py
from django.http import HttpResponse, Http404, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User

# Create your views here.
from member.decorators import login_required
from .forms import PostForm, PostCommentForm
from .models import Post, PostComment


def post_list(request):
    """
    모든 Post목록을 리턴
    template은 'post/post_list.html'사용
    :param request:
    :return:
    """
    if bool(request.user.is_authenticated):
        comment_form = PostCommentForm()
        posts = Post.objects.all()
        context = {
            'posts': posts,
            'comment_form': comment_form,
        }
        return render(request, 'post/post_list.html', context)
    return redirect('member:login')


@login_required
def post_create(request):
    """

    :param request:
    :return:
    """
    if bool(request.user.is_authenticated):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('post:post_list')
        context = {
            'imageform': form,
        }
        return render(request, 'post/post_create.html', context)
    else:
        return redirect('member:login')


def post_delete(request, post_pk):
    next = request.GET.get('next', '').strip()
    post = get_object_or_404(Post, pk=post_pk)
    if post.author == request.user:
        post.delete()
        return redirect(next)
    else:
        return HttpResponseForbidden()


def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = PostCommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,

    }
    return render(request, 'post/post_detail.html', context)


@login_required
def post_like_toggle(request, post_pk):
    """
    post_pk 에 해당하는 Post가
    현재 로그인한 유저의 like_posts에 있다면 없애고
    like_posts에 없다면 추가
    :param request:
    :param post_pk:
    :return:
    """

    next_path = request.GET.get('next')
    post = get_object_or_404(Post, pk=post_pk)
    user = request.user
    filtered_like_posts = user.like_posts.filter(pk=post.pk)
    if filtered_like_posts.exists():
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    if next_path:
        return redirect(next_path)
    return redirect('post:post_detail', post_pk=post_pk)


class PostLikeAPIToggle(APIView):
    """
    View to list all users in the system.

    * Requires token authentication.
    * Only admin users are able to access this view.
    """
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAdminUser,)

    def get(self, request, format=None):
        """
        Return a list of all users.
        """
        usernames = [user.username for user in User.objects.all()]
        return Response(usernames)


def add_comment(request, post_pk):
    if bool(request.user.is_authenticated):
        post = Post.objects.get(pk=post_pk)
        comment = PostCommentForm(request.POST)
        next = request.GET.get('next', '').strip()
        if comment.is_valid():
            new_comment = comment.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
        return redirect(next)
    else:
        return redirect('member:login')


def delete_comment(request, comment_pk):
    next = request.GET.get('next', '').strip()
    comment = get_object_or_404(PostComment, pk=comment_pk)
    if comment.author == request.user:
        comment.delete()
        return redirect(next)
    else:
        return HttpResponseForbidden()

instagram/templates/post/post.html
<div class="row padding-lg-container">
    <div class="container post-container">
        <div class="row">
            <div class="col-md-12">
                <a href="#">{{ post.author }}</a>
                {% if post.author == user %}
                <form class="float-right display-inline"
                      action="{% url 'post:post_delete' post_pk=post.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="fa fa-times"></button>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="row overflow-hidden textalign-center">
            <img class="img-fluid" id="post-photo-{{ post.pk }}" src="{{ post.photo.url }}" alt="image">
        </div>
        <ul class="comments">
            {% for comment in post.comments.all %}
            <li class="col comment"><a href="">{{ comment.author }}</a> {{ comment }}
                {% if comment.author == user %}
                <form class="float-right display-inline"
                      action="{% url 'post:delete_comment' comment_pk=comment.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="fa fa-times"></button>
                </form>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        <div class="comment-form-container clearfix">
            <form method="POST" class="comment-form" action="{% url 'post:add_comment' post_pk=post.pk %}/?next=">
                {{ comment_form }}
                {% csrf_token %}
            </form>

            <!-- Modal beginning -->
            <button class="fa post-options" type="button" class="btn btn-info btn-lg" data-toggle="modal"
                    data-target="#myModal-{{ post.pk }}">&#xf141;
            </button>
            <div id="myModal-{{ post.pk }}" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <button class="post-modal-option btn btn-default"><a href="{{ post.pk }}">게시물로 이동</a></button>
                        <button class="post-modal-option btn btn-default">부적절한 콘텐츠 신고</button>
                        <button class="post-modal-option btn btn-default">퍼가기</button>
                        <button class="post-modal-option btn btn-default" data-dismiss="modal">취소</button>
                    </div>

                </div>
            </div>
            <!-- Modal end -->

        </div>
    </div>
</div>

instagram/templates/post/post_create.html
{% extends 'base.html' %}

{% block content %}
<div class="body-container">
    <div class="container padding-lg-container textalign-center">
        <h1>Upload Photo</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="wrapper">
                {{ imageform.photo }}
                <div id="image-holder"></div>
                <button type="submit" class="btn btn-primary btn-post" value="upload post">upload post</button>
            </div>
        </form>
    </div>
</div>

<script>
$("#id_photo").on('change', function () {

        if (typeof (FileReader) != "undefined") {

            var image_holder = $("#image-holder");
            image_holder.empty();

            var reader = new FileReader();
            reader.onload = function (e) {
                $("<img />", {
                    "src": e.target.result,
                    "class": "thumb-image"
                }).appendTo(image_holder);

            }
            image_holder.show();
            reader.readAsDataURL($(this)[0].files[0]);
        } else {
            alert("This browser does not support FileReader.");
        }
    });


</script>

{% endblock %}

instagram/templates/post/post_detail.html
{% extends 'base.html' %}

<!--Template language의 for구문을 사용해서 각 Post의 photo항목을 출력-->
<!--.photo속성의 'url'속성을 사용해서 img태그를 사용 실제 이미지를 보여주기-->

<!--1. 사진 업로드하기-->
<!--2. 사진에 댓글달기-->
<!--extra1) urls.py모듈을 post애플리케이션 내부에 생성하고,
						include를 이용해서 root urls.py모듈에서 사용-->
<!--extra2) 사진 댓글 지우기, 사진 지우기-->
{% block content %}
<div class="body-container">
    <div class="container">
        {% include "include/post.html" with post_type='detail' %}

    </div>
</div>
{% endblock %}

instagram/templates/post/post_list.html
{% extends 'base.html' %}

<!--Template language의 for구문을 사용해서 각 Post의 photo항목을 출력-->
<!--.photo속성의 'url'속성을 사용해서 img태그를 사용 실제 이미지를 보여주기-->

<!--1. 사진 업로드하기-->
<!--2. 사진에 댓글달기-->
<!--extra1) urls.py모듈을 post애플리케이션 내부에 생성하고,
						include를 이용해서 root urls.py모듈에서 사용-->
<!--extra2) 사진 댓글 지우기, 사진 지우기-->
{% block content %}
<div class="body-container">
    <div class="container">
        {% for post in posts %}
        {% include "include/post.html" with post_type='list' %}
        {% endfor %}
    </div>
</div>


{% endblock %}