instagram/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from .views import landing_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing_page, name='landing_page'),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^member/', include('member.urls', namespace='member')),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

instagram/member/urls.py
from django.conf.urls import url

from member import views

urlpatterns = [
    url(r'^signup', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook_login'),
]

instagram/post/urls.py
from django.conf.urls import url

from post import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^delete/(?P<post_pk>\d+)/$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/like$', views.post_like_toggle, name='post_like_toggle'),
    url(r'^comment/(?P<post_pk>\d+)/$', views.add_comment, name='add_comment'),
    url(r'^comment/(?P<comment_pk>\d+)/delete/$', views.delete_comment, name='delete_comment'),
]

instagram/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% include "head_css.html" %}
    <title>Instagram</title>
</head>
<body>

{% include "navbar.html" %}

{% block content %}
{% endblock %}

</body>

<script>
$('.comment-form').keydown(function(e) {
    if (e.keyCode == 13) {
        $('#form').submit();
    }
});
</script>

<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
</html>

instagram/templates/head_css.html
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
      integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- List js -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>

<!-- Social Icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

instagram/templates/navbar.html
<nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
    <div class="instagram-container container container-fluid">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="instagram-main navbar-brand" href="{% url 'post:post_list' %}"></a>

        {% if user.is_authenticated %}
        <div class="" id="navbarToggler">
            <ul class="navbar-nav">
                <li class="nav-item sidepadding-md-container">
                    <a class="btn btn-primary" href="{% url 'post:post_create' %}">Create Post</a>
                </li>
                <li class="nav-item sidepadding-md-container">
                    <a href="" class="user-icon user-icon-heart"></a>
                </li>
                <li class="nav-item sidepadding-md-container">
                    <a class="user-icon user-icon-user" href="{% url 'member:profile' username=user.username %}">
                    </a>
                </li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>